/**
 * PixelForge v19 — Guide steps
 * Curated walkthrough of the most impactful fixes.
 */

import type { GuideStep } from "../types";

export const GUIDE_STEPS: GuideStep[] = [
  {
    id: "add-meta",
    category: "seo",
    title: "Add a meta description",
    body: "Your page is missing a meta description. Search engines show this in results — without it, they guess from your body copy.",
    do: 'Click "Fix" on the Missing Meta Description issue to add a placeholder, then edit it to be 50-160 chars.',
    impact: "Up to +6 points SEO",
    why: "Pages with descriptive meta descriptions get up to 5.8% more clicks from search results.",
    selector: null,
    quickFix: "addMeta",
  },
  {
    id: "add-h1",
    category: "seo",
    title: "Add an H1 headline",
    body: "Every page needs exactly one H1. It's the most important heading for both SEO and accessibility.",
    do: 'Click "Fix" on the H1 issue. Edit the placeholder text to describe what your page offers.',
    impact: "Up to +8 points SEO",
    why: "Google uses the H1 as a primary signal for what the page is about.",
    selector: null,
    quickFix: "fixMissingH1",
  },
  {
    id: "fix-alt",
    category: "a11y",
    title: "Add alt text to images",
    body: "Images without alt text are invisible to screen readers and bad for SEO.",
    do: 'Click "Fix" on the Missing Alt issue to auto-generate alt text from filenames, then review each.',
    impact: "Up to +7 points Accessibility",
    why: "1 in 4 adults has a disability. Alt text makes your page usable for them and boosts image SEO.",
    selector: null,
    quickFix: "fixAltText",
  },
  {
    id: "fix-viewport",
    category: "structure",
    title: "Add a viewport meta tag",
    body: "Without a viewport tag, mobile browsers render your page at desktop width and zoom out — making text unreadable.",
    do: 'Click "Fix" on the viewport issue. The tag is added automatically.',
    impact: "Up to +5 points Structure",
    why: "Google demotes pages without viewport tags in mobile search results.",
    selector: null,
    quickFix: "addViewport",
  },
  {
    id: "fix-cta",
    category: "content",
    title: "Improve your CTA copy",
    body: "Your call-to-action button text is either missing or weak. Visitors need explicit direction.",
    do: 'Click "Fix" on the CTA issue, then edit the button text to be 2-5 action words like "Start Free".',
    impact: "Up to +13 points Content",
    why: 'CTAs with action verbs convert 2x better than passive ones ("Submit" vs "Start Free").',
    selector: null,
    quickFix: "fixCTACopy",
  },
  {
    id: "fix-font-display",
    category: "perf",
    title: "Add display=swap to Google Fonts",
    body: "Your Google Fonts URL is blocking text rendering on mobile. Add &display=swap to fix it.",
    do: 'Click "Fix" on the font-display issue. The parameter is appended automatically.',
    impact: "Up to +3 points Performance",
    why: "display=swap eliminates FOIT (flash of invisible text) — a top cause of poor mobile PageSpeed scores.",
    selector: null,
    quickFix: "fixFontDisplay",
  },
  {
    id: "add-og",
    category: "seo",
    title: "Add Open Graph tags",
    body: "Without OG tags, sharing your page on social media shows a bare link — no preview image, title, or description.",
    do: 'Click "Fix" on the OG issue to auto-generate all 5 tags. Then customize the image URL.',
    impact: "Up to +5 points SEO",
    why: "Pages with OG tags get 2.3x more engagement when shared on social media.",
    selector: null,
    quickFix: "addOpenGraph",
  },
  {
    id: "add-favicon",
    category: "seo",
    title: "Add a favicon",
    body: "No favicon found. Browsers show a generic icon in tabs and bookmarks.",
    do: 'Click "Fix" to generate a branded SVG favicon with your initial.',
    impact: "Up to +3 points SEO",
    why: "Favicons build brand recognition — they appear in tabs, bookmarks, history, and search results.",
    selector: null,
    quickFix: "addFavicon",
  },
];
